name: Parcel PMS Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [API, UI, HYBRID]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run ${{ matrix.group }} Tests
        run: mvn clean test -Dcucumber.filter.tags="@${{ matrix.group }}" -Dgroups=${{ matrix.group }}

      - name: Generate Allure Results
        if: always()
        run: mvn allure:report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.group }}
          path: target/allure-results

  aggregate-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          path: target/allure-results

      - name: Generate Combined Allure Report
        run: |
          mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
